

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	1EDCF75B05AB6B0F2456D849D6AABE40

; File Name   :	Z:\home\thewormkill\decomp\tests\conditions9
; Format      :	ELF (Executable)
; Interpreter '/lib/ld-linux.so.2'
; Needed Library 'libc.so.6'
;
; Source File :	'init.c'
; Source File :	'crtstuff.c'
; Source File :	'conditions9.c'
; Source File :	'elf-init.c'

.686p
.mmx
.model flat
.intel_syntax noprefix


; Segment type:	Pure code
; Segment permissions: Read/Execute
_init segment dword public 'CODE' use32
assume cs:_init
;org 80482F8h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _init_proc
_init_proc proc	near
push	ebx		; _init
sub	esp, 8
call	__x86_get_pc_thunk_bx
add	ebx, 14A3h
mov	eax, [ebx-0Ch]
test	eax, eax
jz	short loc_8048316
call	___gmon_start__

loc_8048316:
call	frame_dummy
call	__do_global_ctors_aux
add	esp, 8
pop	ebx
retn
_init_proc endp

_init ends


; Segment type:	Pure code
; Segment permissions: Read/Execute
_plt segment para public 'CODE' use32
assume cs:_plt
;org 8048330h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
dd 4 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION ___gmon_start__. PRESS KEYPAD "+"	TO EXPAND]
dw ?
dd 2 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION ___libc_start_main. PRESS	KEYPAD "+" TO EXPAND]
dw ?
dd 2 dup(?)
_plt ends


; Segment type:	Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 8048360h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _start
_start proc near
xor	ebp, ebp
pop	esi
mov	ecx, esp
and	esp, 0FFFFFFF0h
push	eax
push	esp
push	edx
push	offset __libc_csu_fini
push	offset __libc_csu_init
push	ecx
push	esi
push	offset main
call	___libc_start_main
hlt
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
_start endp




public __x86_get_pc_thunk_bx
__x86_get_pc_thunk_bx proc near
mov	ebx, [esp+0]
retn
__x86_get_pc_thunk_bx endp

align 10h


; Attributes: bp-based frame

deregister_tm_clones proc near

var_18=	dword ptr -18h

push	ebp
mov	ebp, esp
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 13FBh
sub	esp, 14h
lea	eax, [ebx+1Fh]
lea	edx, [ebx+1Ch]
sub	eax, edx
cmp	eax, 6
ja	short loc_80483CB

loc_80483C5:
add	esp, 14h
pop	ebx
pop	ebp
retn

loc_80483CB:
mov	eax, [ebx-10h]
test	eax, eax
jz	short loc_80483C5
mov	[esp+18h+var_18], edx
call	eax
jmp	short loc_80483C5
deregister_tm_clones endp

align 10h


; Attributes: bp-based frame

register_tm_clones proc	near

var_18=	dword ptr -18h
var_14=	dword ptr -14h

push	ebp
mov	ebp, esp
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 13BBh
sub	esp, 14h
lea	eax, [ebx+1Ch]
lea	edx, [ebx+1Ch]
sub	eax, edx
sar	eax, 2
mov	ecx, eax
shr	ecx, 1Fh
add	eax, ecx
sar	eax, 1
jnz	short loc_8048414

loc_804840E:
add	esp, 14h
pop	ebx
pop	ebp
retn

loc_8048414:
mov	ecx, [ebx-4]
test	ecx, ecx
jz	short loc_804840E
mov	[esp+18h+var_14], eax
mov	[esp+18h+var_18], edx
call	ecx
jmp	short loc_804840E
register_tm_clones endp

align 10h


; Attributes: bp-based frame

__do_global_dtors_aux proc near
push	ebp
mov	ebp, esp
push	esi
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 136Ah
cmp	byte ptr [ebx+1Ch], 0
jnz	short loc_804848E
mov	eax, [ebx+20h]
lea	esi, [ebx-0E0h]
lea	edx, [ebx-0E4h]
sub	esi, edx
sar	esi, 2
sub	esi, 1
cmp	eax, esi
jnb	short loc_8048482
nop

loc_8048468:
add	eax, 1
mov	[ebx+20h], eax
call	dword ptr [ebx+eax*4-0E4h]
mov	eax, [ebx+20h]
cmp	eax, esi
jb	short loc_8048468

loc_8048482:
call	deregister_tm_clones
mov	byte ptr [ebx+1Ch], 1

loc_804848E:
pop	ebx
pop	esi
pop	ebp
retn
__do_global_dtors_aux endp

align 10h


; Attributes: bp-based frame

frame_dummy proc near

var_18=	dword ptr -18h

push	ebp
mov	ebp, esp
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 12FBh
sub	esp, 14h
mov	eax, [ebx-0DCh]
test	eax, eax
jz	short loc_80484D1
mov	eax, [ebx-8]
test	eax, eax
jz	short loc_80484D1
lea	edx, [ebx-0DCh]
mov	[esp+18h+var_18], edx
call	eax

loc_80484D1:
add	esp, 14h
pop	ebx
pop	ebp
jmp	register_tm_clones
frame_dummy endp

align 4


; Attributes: bp-based frame

public main
main proc near

var_4= dword ptr -4

push	ebp
mov	ebp, esp
sub	esp, 10h
mov	[ebp+var_4], 0
jmp	short loc_80484F7

loc_80484EB:
cmp	[ebp+var_4], 7
jnz	short loc_80484F3
jmp	short locret_80484FD

loc_80484F3:
add	[ebp+var_4], 1

loc_80484F7:
cmp	[ebp+var_4], 13h
jle	short loc_80484EB

locret_80484FD:
leave
retn
main endp

align 10h



public __libc_csu_init
__libc_csu_init	proc near

var_24=	dword ptr -24h
var_20=	dword ptr -20h
var_1C=	dword ptr -1Ch
arg_0= dword ptr  0Ch
arg_4= dword ptr  10h
arg_8= dword ptr  14h

push	ebp
push	edi
xor	edi, edi
push	esi
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 1299h
sub	esp, 1Ch
mov	ebp, [esp+24h+arg_0]
lea	esi, [ebx-0ECh]
call	_init_proc
lea	eax, [ebx-0ECh]
sub	esi, eax
sar	esi, 2
test	esi, esi
jz	short loc_8048559
lea	esi, [esi+0]

loc_8048538:
mov	eax, [esp+24h+arg_8]
mov	[esp+24h+var_24], ebp
mov	[esp+24h+var_1C], eax
mov	eax, [esp+24h+arg_4]
mov	[esp+24h+var_20], eax
call	dword ptr [ebx+edi*4-0ECh]
add	edi, 1
cmp	edi, esi
jnz	short loc_8048538

loc_8048559:
add	esp, 1Ch
pop	ebx
pop	esi
pop	edi
pop	ebp
retn
__libc_csu_init	endp

jmp	short __libc_csu_fini
align 10h



public __libc_csu_fini
__libc_csu_fini	proc near
rep retn
__libc_csu_fini	endp

align 10h


; Attributes: bp-based frame

__do_global_ctors_aux proc near
push	ebp
mov	ebp, esp
push	esi
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 121Ah
mov	eax, [ebx-0ECh]
lea	esi, [ebx-0ECh]
cmp	eax, 0FFFFFFFFh
jz	short loc_80485B4
lea	esi, [esi+0]

loc_80485A8:
sub	esi, 4
call	eax
mov	eax, [esi]
cmp	eax, 0FFFFFFFFh
jnz	short loc_80485A8

loc_80485B4:
pop	ebx
pop	esi
pop	ebp
retn
__do_global_ctors_aux endp

_text ends


; Segment type:	Pure code
; Segment permissions: Read/Execute
_fini segment dword public 'CODE' use32
assume cs:_fini
;org 80485B8h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _term_proc
_term_proc proc	near
push	ebx		; _fini
sub	esp, 8
call	__x86_get_pc_thunk_bx
add	ebx, 11E3h
call	__do_global_dtors_aux
add	esp, 8
pop	ebx
retn
_term_proc endp

_fini ends


; Segment type:	Pure data
; Segment permissions: Read
_rodata	segment	dword public 'CONST' use32
assume cs:_rodata
;org 80485D4h
public _fp_hw
_fp_hw dd 3
public _IO_stdin_used
_IO_stdin_used dd 20001h
_rodata	ends


; Segment type:	Pure data
; Segment permissions: Read
_eh_frame_hdr segment dword public 'CONST' use32
assume cs:_eh_frame_hdr
;org 80485DCh
db    1
db  1Bh
db    3
db  3Bh	; ;
db  28h	; (
db    0
db    0
db    0
db    4
db    0
db    0
db    0
db  54h	; T
db 0FDh	; ý
db 0FFh
db 0FFh
db  44h	; D
db    0
db    0
db    0
db    0
db 0FFh
db 0FFh
db 0FFh
db  68h	; h
db    0
db    0
db    0
db  24h	; $
db 0FFh
db 0FFh
db 0FFh
db  88h	; 
db    0
db    0
db    0
db  94h	; ”
db 0FFh
db 0FFh
db 0FFh
db 0C4h	; ฤ
db    0
db    0
db    0
_eh_frame_hdr ends


; Segment type:	Pure data
; Segment permissions: Read
_eh_frame segment dword	public 'CONST' use32
assume cs:_eh_frame
;org 8048608h
db  14h
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    1
db  7Ah	; z
db  52h	; R
db    0
db    1
db  7Ch	; |
db    8
db    1
db  1Bh
db  0Ch
db    4
db    4
db  88h	; 
db    1
db    0
db    0
db  20h
db    0
db    0
db    0
db  1Ch
db    0
db    0
db    0
db    8
db 0FDh	; ý
db 0FFh
db 0FFh
db  30h	; 0
db    0
db    0
db    0
db    0
db  0Eh
db    8
db  46h	; F
db  0Eh
db  0Ch
db  4Ah	; J
db  0Fh
db  0Bh
db  74h	; t
db    4
db  78h	; x
db    0
db  3Fh	; ?
db  1Ah
db  3Bh	; ;
db  2Ah	; *
db  32h	; 2
db  24h	; $
db  22h	; "
db  1Ch
db    0
db    0
db    0
db  40h	; @
db    0
db    0
db    0
db  90h	; 
db 0FEh	; þ
db 0FFh
db 0FFh
db  23h	; #
db    0
db    0
db    0
db    0
db  41h	; A
db  0Eh
db    8
db  85h	; …
db    2
db  42h	; B
db  0Dh
db    5
db  5Fh	; _
db 0C5h	; ล
db  0Ch
db    4
db    4
db    0
db    0
db  38h	; 8
db    0
db    0
db    0
db  60h	; `
db    0
db    0
db    0
db  94h	; ”
db 0FEh	; þ
db 0FFh
db 0FFh
db  61h	; a
db    0
db    0
db    0
db    0
db  41h	; A
db  0Eh
db    8
db  85h	; …
db    2
db  41h	; A
db  0Eh
db  0Ch
db  87h	; 
db    3
db  43h	; C
db  0Eh
db  10h
db  86h	; 
db    4
db  41h	; A
db  0Eh
db  14h
db  83h	; 
db    5
db  4Eh	; N
db  0Eh
db  30h	; 0
db    2
db  48h	; H
db  0Eh
db  14h
db  41h	; A
db 0C3h	; ร
db  0Eh
db  10h
db  41h	; A
db 0C6h	; ฦ
db  0Eh
db  0Ch
db  41h	; A
db 0C7h	; ว
db  0Eh
db    8
db  41h	; A
db 0C5h	; ล
db  0Eh
db    4
db  10h
db    0
db    0
db    0
db  9Ch	; 
db    0
db    0
db    0
db 0C8h	; ศ
db 0FEh	; þ
db 0FFh
db 0FFh
db    2
db    0
db    0
db    0
db    0
db    0
db    0
db    0
__FRAME_END__ db    0
db    0
db    0
db    0
_eh_frame ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_ctors segment dword public 'DATA' use32
assume cs:_ctors
;org 80496B8h
__CTOR_LIST__ db 0FFh	; Alternative name is '__init_array_end'
db 0FFh
db 0FFh
db 0FFh
__CTOR_END__ db	   0
db    0
db    0
db    0
_ctors ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_dtors segment dword public 'DATA' use32
assume cs:_dtors
;org 80496C0h
__DTOR_LIST__ db 0FFh
db 0FFh
db 0FFh
db 0FFh
public __DTOR_END__
__DTOR_END__ db	   0
db    0
db    0
db    0
_dtors ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_jcr segment dword public 'DATA' use32
assume cs:_jcr
;org 80496C8h
__JCR_LIST__ db	   0
db    0
db    0
db    0
_jcr ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_got segment dword public 'DATA' use32
assume cs:_got
;org 8049794h
dd offset _ITM_deregisterTMCloneTable
dd offset __gmon_start__
dd offset _Jv_RegisterClasses
dd offset _ITM_registerTMCloneTable
_got ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_got_plt segment dword public 'DATA' use32
assume cs:_got_plt
;org 80497A4h
_GLOBAL_OFFSET_TABLE_ db    ? ;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
off_80497B0 dd offset __gmon_start__
off_80497B4 dd offset __libc_start_main
_got_plt ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_data segment dword public 'DATA' use32
assume cs:_data
;org 80497B8h
public data_start ; weak
data_start db	 0	; Alternative name is '__data_start'
db    0
db    0
db    0
public __dso_handle
__dso_handle db	   0
db    0
db    0
db    0
_data ends


; Segment type:	Uninitialized
; Segment permissions: Read/Write
_bss segment dword public 'BSS' use32
assume cs:_bss
;org 80497C0h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
completed_6302 db ?	; Alternative name is '__TMC_END__'
align 4
dtor_idx_6304 dd ?
_bss ends


; Segment type:	Externs
; extern
extrn __libc_start_main@@GLIBC_2_0:near
extrn __libc_start_main:near
extrn _ITM_deregisterTMCloneTable ; weak
extrn __gmon_start__ ; weak
extrn _Jv_RegisterClasses ; weak
extrn _ITM_registerTMCloneTable	; weak


end _start
