

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	A1F2DB98AA964E34D663D32B0CE1B4D7

; File Name   :	Z:\home\thewormkill\Iridium\docs\test
; Format      :	ELF (Executable)
; Interpreter '/lib/ld-linux.so.2'
; Needed Library 'libc.so.6'
;
; Source File :	'init.c'
; Source File :	'crtstuff.c'
; Source File :	'elf-init.c'
; Source File :	'test.c'

.686p
.mmx
.model flat
.intel_syntax noprefix


; Segment type:	Pure code
; Segment permissions: Read/Execute
_init segment dword public 'CODE' use32
assume cs:_init
;org 8048360h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _init_proc
_init_proc proc	near
push	ebx		; _init
sub	esp, 8
call	__x86_get_pc_thunk_bx
add	ebx, 161Bh
mov	eax, [ebx-0Ch]
test	eax, eax
jz	short loc_804837E
call	___gmon_start__

loc_804837E:
call	frame_dummy
call	__do_global_ctors_aux
add	esp, 8
pop	ebx
retn
_init_proc endp

_init ends


; Segment type:	Pure code
; Segment permissions: Read/Execute
_plt segment para public 'CODE' use32
assume cs:_plt
;org 8048390h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
dd 4 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION _puts. PRESS KEYPAD "+" TO EXPAND]
dw ?
dd 2 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION ___gmon_start__. PRESS KEYPAD "+"	TO EXPAND]
dw ?
dd 2 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION ___libc_start_main. PRESS	KEYPAD "+" TO EXPAND]
dw ?
dd 2 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION ___isoc99_scanf. PRESS KEYPAD "+"	TO EXPAND]
dw ?
dd 2 dup(?)
_plt ends


; Segment type:	Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 80483E0h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _start
_start proc near
xor	ebp, ebp
pop	esi
mov	ecx, esp
and	esp, 0FFFFFFF0h
push	eax
push	esp
push	edx
push	offset __libc_csu_fini
push	offset __libc_csu_init
push	ecx
push	esi
push	offset main
call	___libc_start_main
hlt
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
db	66h
nop
_start endp




public __x86_get_pc_thunk_bx
__x86_get_pc_thunk_bx proc near
mov	ebx, [esp+0]
retn
__x86_get_pc_thunk_bx endp

align 10h


; Attributes: bp-based frame

deregister_tm_clones proc near

var_4= dword ptr -4

push	ebp
mov	ebp, esp
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 155Bh
sub	esp, 4
lea	edx, [ebx+24h]
lea	eax, [ebx+27h]
sub	eax, edx
cmp	eax, 6
jbe	short loc_8048458
mov	eax, [ebx-10h]
test	eax, eax
jz	short loc_8048458
sub	esp, 0Ch
push	edx
call	eax
add	esp, 10h

loc_8048458:
mov	ebx, [ebp+var_4]
leave
retn
deregister_tm_clones endp

align 10h


; Attributes: bp-based frame

register_tm_clones proc	near

var_4= dword ptr -4

push	ebp
mov	ebp, esp
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 151Bh
sub	esp, 4
lea	edx, [ebx+24h]
lea	eax, [ebx+24h]
sub	eax, edx
sar	eax, 2
mov	ecx, eax
shr	ecx, 1Fh
add	eax, ecx
sar	eax, 1
jz	short loc_80484A2
mov	ecx, [ebx-4]
test	ecx, ecx
jz	short loc_80484A2
sub	esp, 8
push	eax
push	edx
call	ecx
add	esp, 10h

loc_80484A2:
mov	ebx, [ebp+var_4]
leave
retn
register_tm_clones endp

align 10h


; Attributes: bp-based frame

__do_global_dtors_aux proc near
push	ebp
mov	ebp, esp
push	esi
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 14CAh
cmp	byte ptr [ebx+24h], 0
jnz	short loc_8048516
lea	edx, [ebx-0E4h]
lea	esi, [ebx-0E0h]
mov	eax, [ebx+28h]
sub	esi, edx
sar	esi, 2
sub	esi, 1
cmp	eax, esi
jnb	short loc_804850A
mov	esi, esi
lea	edi, [edi+0]

loc_80484F0:
add	eax, 1
mov	[ebx+28h], eax
call	dword ptr [ebx+eax*4-0E4h]
mov	eax, [ebx+28h]
cmp	eax, esi
jb	short loc_80484F0

loc_804850A:
call	deregister_tm_clones
mov	byte ptr [ebx+24h], 1

loc_8048516:
pop	ebx
pop	esi
pop	ebp
retn
__do_global_dtors_aux endp

align 10h


; Attributes: bp-based frame

frame_dummy proc near

var_4= dword ptr -4

push	ebp
mov	ebp, esp
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 145Bh
sub	esp, 4
lea	eax, [ebx-0DCh]
mov	edx, [eax]
test	edx, edx
jnz	short loc_8048550

loc_804853E:
mov	ebx, [ebp+var_4]
leave
jmp	register_tm_clones
align 10h

loc_8048550:
mov	edx, [ebx-8]
test	edx, edx
jz	short loc_804853E
sub	esp, 0Ch
push	eax
call	edx
add	esp, 10h
jmp	short loc_804853E
frame_dummy endp



; Attributes: bp-based frame

public main
main proc near

var_2C=	dword ptr -2Ch
var_18=	dword ptr -18h
var_14=	dword ptr -14h
var_10=	dword ptr -10h
var_C= dword ptr -0Ch
var_4= dword ptr -4
arg_0= dword ptr  4

lea	ecx, [esp+arg_0]
and	esp, 0FFFFFFF0h
push	dword ptr [ecx-4]
push	ebp
mov	ebp, esp
push	ecx
sub	esp, 34h
sub	esp, 0Ch
push	offset aEingabeInBuffe ; "Eingabe in Buffer (20	Zeichen): "
call	_puts
add	esp, 10h
sub	esp, 8
lea	eax, [ebp+var_2C]
push	eax
push	offset a20s	; "%20s"
call	___isoc99_scanf
add	esp, 10h
sub	esp, 0Ch
push	offset aAnzahlSchleife ; "Anzahl Schleifendurchlรคufe: "
call	_puts
add	esp, 10h
sub	esp, 8
lea	eax, [ebp+var_14]
push	eax
push	offset aD	; "%d"
call	___isoc99_scanf
add	esp, 10h
mov	[ebp+var_C], 0
jmp	short loc_8048630

loc_80485C7:
sub	esp, 0Ch
push	offset aAnzahlInnererS ; "Anzahl innerer Schleifendurchlรคufe: "
call	_puts
add	esp, 10h
sub	esp, 8
lea	eax, [ebp+var_18]
push	eax
push	offset aD	; "%d"
call	___isoc99_scanf
add	esp, 10h
mov	[ebp+var_10], 0
jmp	short loc_8048624

loc_80485F4:
mov	eax, [ebp+var_10]
and	eax, 1
test	eax, eax
jnz	short loc_8048610
sub	esp, 0Ch
push	offset aDGerade_ ; "d gerade."
call	_puts
add	esp, 10h
jmp	short loc_8048620

loc_8048610:
sub	esp, 0Ch
push	offset aDUngerade_ ; "d	ungerade."
call	_puts
add	esp, 10h

loc_8048620:
add	[ebp+var_10], 1

loc_8048624:
mov	eax, [ebp+var_18]
cmp	[ebp+var_10], eax
jl	short loc_80485F4
add	[ebp+var_C], 1

loc_8048630:
mov	eax, [ebp+var_14]
cmp	[ebp+var_C], eax
jl	short loc_80485C7
mov	eax, 0
mov	ecx, [ebp+var_4]
leave
lea	esp, [ecx-4]
retn
main endp ; sp =  4

align 10h



public __libc_csu_init
__libc_csu_init	proc near

var_30=	dword ptr -30h
var_2C=	dword ptr -2Ch
var_28=	dword ptr -28h
var_14=	dword ptr -14h
arg_0= dword ptr  10h
arg_4= dword ptr  14h
arg_8= dword ptr  18h

push	ebp
push	edi
push	esi
xor	esi, esi
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 1329h
sub	esp, 2Ch
mov	ebp, [esp+30h+arg_0]
mov	edi, [esp+30h+arg_4]
call	_init_proc
lea	eax, [ebx-0ECh]
lea	edx, [ebx-0ECh]
sub	edx, eax
sar	edx, 2
mov	[esp+30h+var_14], edx
jz	short loc_80486AD
nop
lea	esi, [esi+0]

loc_8048690:
mov	eax, [esp+30h+arg_8]
mov	[esp+30h+var_2C], edi
mov	[esp+30h+var_30], ebp
mov	[esp+30h+var_28], eax
call	dword ptr [ebx+esi*4-0ECh]
inc	esi
cmp	esi, [esp+30h+var_14]
jnz	short loc_8048690

loc_80486AD:
add	esp, 2Ch
pop	ebx
pop	esi
pop	edi
pop	ebp
retn
__libc_csu_init	endp

align 10h



public __libc_csu_fini
__libc_csu_fini	proc near
retn
__libc_csu_fini	endp

align 10h


; Attributes: bp-based frame

__do_global_ctors_aux proc near
push	ebp
mov	ebp, esp
push	esi
push	ebx
call	__x86_get_pc_thunk_bx
add	ebx, 12AAh
mov	eax, [ebx-0ECh]
lea	esi, [ebx-0ECh]
cmp	eax, 0FFFFFFFFh
jz	short loc_8048704
lea	esi, [esi+0]

loc_80486F8:
sub	esi, 4
call	eax
mov	eax, [esi]
cmp	eax, 0FFFFFFFFh
jnz	short loc_80486F8

loc_8048704:
pop	ebx
pop	esi
pop	ebp
retn
__do_global_ctors_aux endp

_text ends


; Segment type:	Pure code
; Segment permissions: Read/Execute
_fini segment dword public 'CODE' use32
assume cs:_fini
;org 8048708h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public _term_proc
_term_proc proc	near
push	ebx		; _fini
sub	esp, 8
call	__x86_get_pc_thunk_bx
add	ebx, 1273h
call	__do_global_dtors_aux
add	esp, 8
pop	ebx
retn
_term_proc endp

_fini ends


; Segment type:	Pure data
; Segment permissions: Read
_rodata	segment	dword public 'CONST' use32
assume cs:_rodata
;org 8048724h
public _fp_hw
_fp_hw dd 3
public _IO_stdin_used
_IO_stdin_used dd 20001h
; char aEingabeInBuffe[]
aEingabeInBuffe	db 'Eingabe in Buffer (20 Zeichen): ',0
a20s db	'%20s',0
; char aAnzahlSchleife[]
aAnzahlSchleife	db 'Anzahl Schleifendurchlรคufe: ',0
aD db '%d',0
align 4
; char aAnzahlInnererS[]
aAnzahlInnererS	db 'Anzahl innerer Schleifendurchlรคufe'
db ': ',0
; char aDGerade_[]
aDGerade_ db 'd gerade.',0
; char aDUngerade_[]
aDUngerade_ db 'd ungerade.',0
_rodata	ends


; Segment type:	Pure data
; Segment permissions: Read
_eh_frame_hdr segment dword public 'CONST' use32
assume cs:_eh_frame_hdr
;org 80487B0h
db    1
db  1Bh
db    3
db  3Bh	; ;
db  28h	; (
db    0
db    0
db    0
db    4
db    0
db    0
db    0
db 0E0h	; เ
db 0FBh	; ๛
db 0FFh
db 0FFh
db  44h	; D
db    0
db    0
db    0
db 0B5h	; ต
db 0FDh	; ý
db 0FFh
db 0FFh
db  68h	; h
db    0
db    0
db    0
db 0A0h	;  
db 0FEh	; þ
db 0FFh
db 0FFh
db  94h	; ”
db    0
db    0
db    0
db  10h
db 0FFh
db 0FFh
db 0FFh
db 0D0h	; ะ
db    0
db    0
db    0
_eh_frame_hdr ends


; Segment type:	Pure data
; Segment permissions: Read
_eh_frame segment dword	public 'CONST' use32
assume cs:_eh_frame
;org 80487DCh
db  14h
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    1
db  7Ah	; z
db  52h	; R
db    0
db    1
db  7Ch	; |
db    8
db    1
db  1Bh
db  0Ch
db    4
db    4
db  88h	; 
db    1
db    0
db    0
db  20h
db    0
db    0
db    0
db  1Ch
db    0
db    0
db    0
db  94h	; ”
db 0FBh	; ๛
db 0FFh
db 0FFh
db  50h	; P
db    0
db    0
db    0
db    0
db  0Eh
db    8
db  46h	; F
db  0Eh
db  0Ch
db  4Ah	; J
db  0Fh
db  0Bh
db  74h	; t
db    4
db  78h	; x
db    0
db  3Fh	; ?
db  1Ah
db  3Bh	; ;
db  2Ah	; *
db  32h	; 2
db  24h	; $
db  22h	; "
db  28h	; (
db    0
db    0
db    0
db  40h	; @
db    0
db    0
db    0
db  45h	; E
db 0FDh	; ý
db 0FFh
db 0FFh
db 0E0h	; เ
db    0
db    0
db    0
db    0
db  44h	; D
db  0Ch
db    1
db    0
db  47h	; G
db  10h
db    5
db    2
db  75h	; u
db    0
db  43h	; C
db  0Fh
db    3
db  75h	; u
db  7Ch	; |
db    6
db    2
db 0CDh	; อ
db  0Ch
db    1
db    0
db  41h	; A
db 0C5h	; ล
db  43h	; C
db  0Ch
db    4
db    4
db  38h	; 8
db    0
db    0
db    0
db  6Ch	; l
db    0
db    0
db    0
db    4
db 0FEh	; þ
db 0FFh
db 0FFh
db  65h	; e
db    0
db    0
db    0
db    0
db  41h	; A
db  0Eh
db    8
db  85h	; …
db    2
db  41h	; A
db  0Eh
db  0Ch
db  87h	; 
db    3
db  41h	; A
db  0Eh
db  10h
db  86h	; 
db    4
db  43h	; C
db  0Eh
db  14h
db  83h	; 
db    5
db  4Eh	; N
db  0Eh
db  40h	; @
db    2
db  4Ch	; L
db  0Eh
db  14h
db  41h	; A
db 0C3h	; ร
db  0Eh
db  10h
db  41h	; A
db 0C6h	; ฦ
db  0Eh
db  0Ch
db  41h	; A
db 0C7h	; ว
db  0Eh
db    8
db  41h	; A
db 0C5h	; ล
db  0Eh
db    4
db  10h
db    0
db    0
db    0
db 0A8h	; จ
db    0
db    0
db    0
db  38h	; 8
db 0FEh	; þ
db 0FFh
db 0FFh
db    1
db    0
db    0
db    0
db    0
db    0
db    0
db    0
__FRAME_END__ db    0
db    0
db    0
db    0
_eh_frame ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_ctors segment dword public 'DATA' use32
assume cs:_ctors
;org 8049898h
__CTOR_LIST__ db 0FFh	; Alternative name is '__init_array_end'
db 0FFh
db 0FFh
db 0FFh
__CTOR_END__ db	   0
db    0
db    0
db    0
_ctors ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_dtors segment dword public 'DATA' use32
assume cs:_dtors
;org 80498A0h
__DTOR_LIST__ db 0FFh
db 0FFh
db 0FFh
db 0FFh
public __DTOR_END__
__DTOR_END__ db	   0
db    0
db    0
db    0
_dtors ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_jcr segment dword public 'DATA' use32
assume cs:_jcr
;org 80498A8h
__JCR_LIST__ db	   0
db    0
db    0
db    0
_jcr ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_got segment dword public 'DATA' use32
assume cs:_got
;org 8049974h
dd offset _ITM_deregisterTMCloneTable
dd offset __gmon_start__
dd offset _Jv_RegisterClasses
dd offset _ITM_registerTMCloneTable
_got ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_got_plt segment dword public 'DATA' use32
assume cs:_got_plt
;org 8049984h
_GLOBAL_OFFSET_TABLE_ db    ? ;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
db    ?	;
off_8049990 dd offset puts
off_8049994 dd offset __gmon_start__
off_8049998 dd offset __libc_start_main
off_804999C dd offset __isoc99_scanf
_got_plt ends


; Segment type:	Pure data
; Segment permissions: Read/Write
_data segment dword public 'DATA' use32
assume cs:_data
;org 80499A0h
public data_start ; weak
data_start db	 0	; Alternative name is '__data_start'
db    0
db    0
db    0
public __dso_handle
__dso_handle db	   0
db    0
db    0
db    0
_data ends


; Segment type:	Uninitialized
; Segment permissions: Read/Write
_bss segment dword public 'BSS' use32
assume cs:_bss
;org 80499A8h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
completed_6586 db ?	; Alternative name is '__TMC_END__'
align 4
dtor_idx_6588 dd ?
_bss ends


; Segment type:	Externs
; extern
extrn puts@@GLIBC_2_0:near
extrn __libc_start_main@@GLIBC_2_0:near
extrn __isoc99_scanf@@GLIBC_2_7:near
; int puts(const char *)
extrn puts:near
extrn __libc_start_main:near
extrn __isoc99_scanf:near
extrn _ITM_deregisterTMCloneTable ; weak
extrn __gmon_start__ ; weak
extrn _Jv_RegisterClasses ; weak
extrn _ITM_registerTMCloneTable	; weak


end _start
